# Generated by Django 3.2.16 on 2023-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
